### PR TITLE
align buffer chunks to sizeof(void*) instead of hard coding 8 bytes

### PR DESCRIPTION
**Pull request by dodsonmg**
Currently, buffer chunks are aligned to a hard-coded 8 bytes.  This is causing exceptions on my research system which uses 16 byte pointers.

This PR generalises the alignment to `sizeof(void *)`, which will work on my system and has the side-effect of future-proofing the code segment.

See a longer discussion of where the trap occurs in issue #497.

### CODE REVIEW

**Comment by dodsonmg** [comment]
This appears to be failing with the following:

```
/home/travis/build/eclipse-cyclonedds/cyclonedds/src/core/ddsi/src/q_radmin.c:310:31: error: conversion from ‘size_t’ {aka ‘long unsigned int’} to ‘uint32_t’ {aka ‘unsigned int’} may change value [-Werror=conversion]
   return (x + align_size - 1) & (uint32_t)-align_size;
```

This isn't a practical problem, because `align_size` holds the size of a `void *` (16 bytes in my case, 8 in most others), so the cast to `uint32_t` won't lose anything.

I can make a modification to avoid the warning, but I think it's cleanest as is.  Since the function returns `uint32_t`, there's going to be a conversion where, since `sizeof` returns `size_t`.

What's your preference?

**Comment by dodsonmg** [comment]
One possibility which builds on Ubuntu 18.04 with gcc:

```
static uint32_t align_literal_uint32 (uint32_t x)
{
  uint32_t align_size = sizeof(void *) > 8 ? sizeof(void *) : 8;
  return (x + align_size - 1) & -align_size;
}
```

This changes `align_size` from `size_t` to `uint32_t` and removes the cast in the return statement.  Since the conditional assignment will resolve to `8`, it seems to be quite happy assigning that to `uint32_t align_size`.

This also builds for my target using clang and 16 byte pointers.  I'll revise the PR.

**Comment by dodsonmg** [comment]
I can't see why the Windows checks are failing.  Seems to be script-related, rather than my PR, but I'm not sure.

File: src/core/ddsi/src/q_radmin.c [hunk 1]
```diff
@@ -14,6 +14,7 @@
 #include <stdarg.h>
 #include <stdlib.h>
 #include <limits.h>
+#include <stdalign.h>
```
Comment (rotu) [inline src/core/ddsi/src/q_radmin.c:17]: were you going to use this? It seems to be C++ and later.

File: src/core/ddsi/src/q_radmin.c [hunk 2]
```diff
@@ -303,9 +304,10 @@ static void nn_rbuf_release (struct nn_rbuf *rbuf);
 #define RMSGTRACE(...)              TRACE_CFG (rmsg, rmsg->chunk.rbuf->rbufpool->logcfg, __VA_ARGS__)
 #define RDATATRACE(rdata, ...)      TRACE_CFG ((rdata)->rmsg, (rdata)->rmsg->chunk.rbuf->rbufpool->logcfg, __VA_ARGS__)
 
-static uint32_t align8uint32 (uint32_t x)
+static uint32_t align_literal_uint32 (uint32_t x)
```
Comment (rotu) [inline src/core/ddsi/src/q_radmin.c:307]: It would be nice to have a why in here. "align_literal_uint32" doesn't make it clear that this is for aligning a `struct nn_rmsg`.

**Comment by eboasson** [comment]
> This appears to be failing with the following:
> 
> ```
> /home/travis/build/eclipse-cyclonedds/cyclonedds/src/core/ddsi/src/q_radmin.c:310:31: error: conversion from ‘size_t’ {aka ‘long unsigned int’} to ‘uint32_t’ {aka ‘unsigned int’} may change value [-Werror=conversion]
>    return (x + align_size - 1) & (uint32_t)-align_size;
> ```
> 
> This isn't a practical problem, because `align_size` holds the size of a `void *` (16 bytes in my case, 8 in most others), so the cast to `uint32_t` won't lose anything.
> 
> I can make a modification to avoid the warning, but I think it's cleanest as is. Since the function returns `uint32_t`, there's going to be a conversion where, since `sizeof` returns `size_t`.
> 
> What's your preference?

I suspect it was GCC ultimately complaining about the conversion of `sizeof(void*)` to an `uint32_t` because it has the friendly habit of (still) not taking into consideration the value of a compile time constant being converted, like clang does. There are also some compilers that warn if you negate an unsigned value, so `-align_size` can cause warnings by itself.

I've found that I get in the least trouble with the various compilers (and compiler versions) if I effectively write it like this:
```C
T align(T x, U a) { const T m = (T)(a-1); return (T) ((x+m) & ~m); }
```
and it all comes down to the same thing anyway ... (That cast of the return value is because a T narrower than an `int` will promote everything to `int`, and with some compilers causes that same warning you got. C's type system makes superficial sense at best.)

File: src/core/ddsi/src/q_radmin.c (hunk 1 above)
Comment (eboasson) [reply src/core/ddsi/src/q_radmin.c:17]: @dodsonmg no surprise there, it is very hard to spot the error on Windows, but this here is indeed the reason:
```
C:\Users\travis\build\eclipse-cyclonedds\cyclonedds\src\core\ddsi\src\q_radmin.c(17): fatal error C1083: Cannot open include file: 'stdalign.h': No such file or directory [C:\Users\travis\build\eclipse-cyclonedds\cyclonedds\build\src\core\ddsc.vcxproj]
```

File: src/core/ddsi/src/q_radmin.c (hunk 2 above)
Comment (eboasson) [reply src/core/ddsi/src/q_radmin.c:307]: Fair point, maybe `align8Puint32` would be better? 8 bytes or pointer, whichever is widest.

Anyway, I'm not known for consistently coming up with beautiful names, so I am not going to fuss over the name of some very locally used alignment function ...

Comment (rotu) [reply src/core/ddsi/src/q_radmin.c:307]: `align8Puint32` is correct but doesn’t make the code any more self-evident. Maybe `align_rmsg` or change it to be a general alignment function that takes as an argument a constant `ALIGNOF_RMSG`.

**Comment by rotu** [comment]
While we're sharing favorite alignment expressions, the version I find most intuitive is this lovely couplet:
```
x += align - 1;
x -= x % align;
```

With power of 2 alignment and unsigned arguments, this simplifies to: `(x + -x % align)`.

There's also the slightly less readable but cute (again, unsigned and powers of 2 alignment):

`( x | (align-1)) + 1`

File: src/core/ddsi/src/q_radmin.c (hunk 1 above)
Comment (dodsonmg) [reply src/core/ddsi/src/q_radmin.c:17]: I agree.  This is unnecessary since I'm using `sizeof` instead of `alignof`.

File: src/core/ddsi/src/q_radmin.c (hunk 2 above)
Comment (dodsonmg) [reply src/core/ddsi/src/q_radmin.c:307]: This makes sense.  How about:

```
static uint32_t align_rmsg (uint32_t x)
{
  /* Align rmsg chunks to the larger of sizeof(void*) or 8.
  Ideally, we would use C11's alignof(void *), but sizeof(void *) is equivalent
  for primitive types. */
  const uint32_t align_size = sizeof(void *) > 8 ? sizeof(void *) : 8;
  return (x + align_size - 1) & -align_size;
}
```

and then returning to the original naming convention for the lhs of the assignment.  For example:

`uint32_t size8P = align_rmsg (size);`

**Comment by eboasson** [comment]
Bummer ... Microsoft struck again ...
```
  q_radmin.c
C:\Users\travis\build\eclipse-cyclonedds\cyclonedds\src\core\ddsi\src\q_radmin.c(312): error C2220: warning treated as error - no 'object' file generated [C:\Users\travis\build\eclipse-cyclonedds\cyclonedds\build\src\core\ddsc.vcxproj]
C:\Users\travis\build\eclipse-cyclonedds\cyclonedds\src\core\ddsi\src\q_radmin.c(312): warning C4146: unary minus operator applied to unsigned type, result still unsigned [C:\Users\travis\build\eclipse-cyclonedds\cyclonedds\build\src\core\ddsc.vcxproj]
```

**Comment by dodsonmg** [comment]
I guess I'll try to be very explicit to get through the MS check.  I've taken a simple, one line function and made if four lines.  Blah.

File: src/core/ddsi/src/q_radmin.c [hunk 3]
```diff
@@ -303,9 +303,15 @@ static void nn_rbuf_release (struct nn_rbuf *rbuf);
 #define RMSGTRACE(...)              TRACE_CFG (rmsg, rmsg->chunk.rbuf->rbufpool->logcfg, __VA_ARGS__)
 #define RDATATRACE(rdata, ...)      TRACE_CFG ((rdata)->rmsg, (rdata)->rmsg->chunk.rbuf->rbufpool->logcfg, __VA_ARGS__)
 
-static uint32_t align8uint32 (uint32_t x)
+static uint32_t align_rmsg (uint32_t x)
 {
-  return (x + 7u) & (uint32_t)-8;
+  /* Align rmsg chunks to the larger of sizeof(void*) or 8.
+  Ideally, we would use C11's alignof(void *), but sizeof(void *) is equivalent
```
Comment (rotu) [inline src/core/ddsi/src/q_radmin.c:309]: `alignof` can be used on aggregate types, so ideally we’d use `alignof(struct nn_rmsg)` rather than assuming “the strictest alignment need of rmsg comes from either uint32 or void*”

File: src/core/ddsi/src/q_radmin.c [hunk 4]
```diff
@@ -620,7 +626,7 @@ void nn_rmsg_commit (struct nn_rmsg *rmsg)
   ASSERT_RBUFPOOL_OWNER (chunk->rbuf->rbufpool);
   ASSERT_RMSG_UNCOMMITTED (rmsg);
   assert (chunk->u.size <= chunk->rbuf->max_rmsg_size);
-  assert ((chunk->u.size % 8) == 0);
+  assert ((chunk->u.size % (sizeof(void *) > 8 ? sizeof(void *) : 8)) == 0);
```
Comment (rotu) [inline src/core/ddsi/src/q_radmin.c:629]: Maybe extract to a constant `ALIGNOF_RMSG`

File: src/core/ddsi/src/q_radmin.c (hunk 3 above)
Comment (dodsonmg) [reply src/core/ddsi/src/q_radmin.c:309]: That makes sense.  I'll revise.

**Comment by rotu** [comment]
> Bummer ... Microsoft struck again ...
> 
> ```
>   q_radmin.c
> C:\Users\travis\build\eclipse-cyclonedds\cyclonedds\src\core\ddsi\src\q_radmin.c(312): error C2220: warning treated as error - no 'object' file generated [C:\Users\travis\build\eclipse-cyclonedds\cyclonedds\build\src\core\ddsc.vcxproj]
> C:\Users\travis\build\eclipse-cyclonedds\cyclonedds\src\core\ddsi\src\q_radmin.c(312): warning C4146: unary minus operator applied to unsigned type, result still unsigned [C:\Users\travis\build\eclipse-cyclonedds\cyclonedds\build\src\core\ddsc.vcxproj]
> ```

Yeah. I understand why Visual Studio alerts on this, and the warning is sensible. It's not totally intuitive that `-(1u)` is unsigned whereas `-(1)` is signed. It's totally legit code but to make MS happy, `(0u-x)` is a more explicit version of `-x`.

File: src/core/ddsi/src/q_radmin.c (hunk 4 above)
Comment (dodsonmg) [reply src/core/ddsi/src/q_radmin.c]: just pushed a change.  see if it builds...

**Comment by dodsonmg** [comment]
I'm getting gcc warnings about size_t -> uint32_t again...

Sorry.  I pushed as a shortcut to move code from one place to another for testing and forgot it would rebuild here automatically...

**Comment by dodsonmg** [comment]
That last push includes a cast to avoid the gcc warnings (and also gets rid of trailing whitespace).

**Comment by eboasson** [comment]
> > Bummer ... Microsoft struck again ...
> > ```
> >   q_radmin.c
> > C:\Users\travis\build\eclipse-cyclonedds\cyclonedds\src\core\ddsi\src\q_radmin.c(312): error C2220: warning treated as error - no 'object' file generated [C:\Users\travis\build\eclipse-cyclonedds\cyclonedds\build\src\core\ddsc.vcxproj]
> > C:\Users\travis\build\eclipse-cyclonedds\cyclonedds\src\core\ddsi\src\q_radmin.c(312): warning C4146: unary minus operator applied to unsigned type, result still unsigned [C:\Users\travis\build\eclipse-cyclonedds\cyclonedds\build\src\core\ddsc.vcxproj]
> > ```
> 
> Yeah. I understand why Visual Studio alerts on this, and the warning is sensible. It's not totally intuitive that `-(1u)` is unsigned whereas `-(1)` is signed. It's totally legit code but to make MS happy, `(0u-x)` is a more explicit version of `-x`.

Not trying to get into a senseless discussion here, but I'd say this is one of the milder cases of arithmetical counter-intuitiveness in C. For example:
```C
# cat > xx.c
#include <stdio.h>
#include <stdlib.h>
int f (uint8_t x)
{
  return (x + x > (uint8_t)255);
}
int g (uint8_t x)
{
#define x2 x*x
#define x4 x2*x2
#define x8 x4*x4
  return (x8 >= (uint8_t)0);
}
int main (int argc, char **argv)
{
  const uint8_t x = (uint8_t) atoi (argv[1]);
  printf ("%d + %d > 255   %s\n", x, x, f (x) ? "true" : "false");
  printf ("%d ** 8 >= 0   %s\n", x, g (x) ? "true" : "false");
  return 0;
}
# clang -g -fsanitize=undefined -Wall xx.c -o xx
# ./xx 255                                          
255 + 255 > 255   true
/Users/erik/C/xx.c:12:11: runtime error: signed integer overflow: 16581375 * 255 cannot be represented in type 'int'
/Users/erik/C/xx.c:12:11: runtime error: signed integer overflow: -66716671 * 255 cannot be represented in type 'int'
/Users/erik/C/xx.c:12:11: runtime error: signed integer overflow: 167118079 * 255 cannot be represented in type 'int'
/Users/erik/C/xx.c:12:11: runtime error: signed integer overflow: -334562815 * 255 cannot be represented in type 'int'
/Users/erik/C/xx.c:12:11: runtime error: signed integer overflow: 585828095 * 255 cannot be represented in type 'int'
255 ** 8 >= 0   false
```
The first is an expression with *only* unsigned 8-bit numbers, and so I would say the intuitive result would be 254, which is less than 255 ... But whatever. I'm sure Microsoft knows best what's good for me, and that is: negating an unsigned integer is scary and needs a warning but implicit promotion to signed integer (possibly triggering undefined behaviour where that's impossible for unsigned types) is perfectly logical ...

Oh well. Rant over 🙂

@dodsonmg Thank you very much, PR looks good to me!
