### ISSUE TITLE
Building in MIngw 8.1.0 x64 (Windows 10)

### ISSUE THREAD

**Issue by j2doll** [eclipse-cyclonedds/cyclonedds#742]
Hi!
Thanks for good code.
I can not speak English well. Please speak very, very easy English.

- I did the following:

:one: Get code from github 
```cmd
git clone https://github.com/eclipse-cyclonedds/cyclonedds.git
```

:two: Install bison using choco
```
choco install winflexbison3
```

:three: Build in MinGW 8.1.0 x64 (Microsoft Windows 10)
```mingw
cd cyclonedds
mkdir build
cd build
cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=D:\cyclonedds\mingw-8-1-0-x64 ..
cmake --build .
```

💣 Build is failed.
```
[ 11%] Building C object src/tools/ddsconf/CMakeFiles/ddsconf.dir/__/__/ddsrt/src/ifaddrs/windows/ifaddrs.c.obj
D:\workspace\github\cyclonedds\src\ddsrt\src\ifaddrs\windows\ifaddrs.c: In function 'copyname':
D:\workspace\github\cyclonedds\src\ddsrt\src\ifaddrs\windows\ifaddrs.c:177:14: error: 'WC_ERR_INVALID_CHARS' undeclared (first use in this function); did you mean 'MB_ERR_INVALID_CHARS'?
     CP_UTF8, WC_ERR_INVALID_CHARS, wstr, -1, buf, 0, NULL, NULL);
              ^~~~~~~~~~~~~~~~~~~~
              MB_ERR_INVALID_CHARS
D:\workspace\github\cyclonedds\src\ddsrt\src\ifaddrs\windows\ifaddrs.c:177:14: note: each undeclared identifier is reported only once for each function it appears in
D:\workspace\github\cyclonedds\src\ddsrt\src\ifaddrs\windows\ifaddrs.c:180:36: warning: conversion to 'size_t' {aka 'long long unsigned int'} from 'int' may change the sign of the result [-Wsign-conversion]
   } else if ((str = ddsrt_malloc_s(len)) == NULL) {
                                    ^~~
D:\workspace\github\cyclonedds\src\ddsrt\src\ifaddrs\windows\ifaddrs.c:173:7: warning: variable 'cnt' set but not used
-Wunused-but-set-variable]
   int cnt, len;
       ^~~
mingw32-make.exe[2]: *** [src\tools\ddsconf\CMakeFiles\ddsconf.dir\build.make:466: src/tools/ddsconf/CMakeFiles/ddsconf.dir/__/__/ddsrt/src/ifaddrs/windows/ifaddrs.c.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:447: src/tools/ddsconf/CMakeFiles/ddsconf.dir/all] Error 2
mingw32-make.exe: *** [Makefile:135: all] Error 
```

**Comment by k0ekk0ek** [comment]
Hi @j2doll. [A quick search on the internet](https://www.mail-archive.com/mingw-w64-public@lists.sourceforge.net/msg03903.html) shows `WC_ERR_INVALID_CHARS` should be available in MinGW, so it's probably some header that is not pulled in(?) I don't think anyone tried to compile with MinGW on Windows before. I'll try to reproduce, the steps you took seem correct at first glance.

**Comment by k0ekk0ek** [comment]
I get the same result. When compiling it seems `winnls.h` from the MinGW directory isn't included, so I'm not exactly sure what's going on yet, but I don't currently have much time to spend on it. For the time being, perhaps you can try building with Visual Studio?

**Comment by j2doll** [comment]
Dear @k0ekk0ek 
Thank you for reporting. 
I want to use gcc in Windows. So I use MingW.

**Comment by k0ekk0ek** [comment]
Hi @j2doll. It's been a while, but #842 makes Cyclone DDS compile cleanly with MinGW. Probably won't make it into the master branch before the 0.8.0 release, but you can give it a try if you want.

**Comment by k0ekk0ek** [comment]
Closed via #842.
